INSERT INTO PLANET (ID, NAME, RADIUS, ORBIT_RADIUS, COLOR, DESCRIPTION)
  VALUES (1, 'Mercury', 4, 100, 'rgb(189, 137, 62)', 'First planet.');

INSERT INTO PLANET (ID, NAME, RADIUS, ORBIT_RADIUS, COLOR, DESCRIPTION)
  VALUES (2, 'Venus', 5, 120, 'rgb(243, 167, 130)', 'Second planet.');

INSERT INTO PLANET (ID, NAME, RADIUS, ORBIT_RADIUS, COLOR, DESCRIPTION)
  VALUES (3, 'Earth', 6, 140, 'rgb(123, 193, 94)', 'Third planet.');

INSERT INTO PLANET (ID, NAME, RADIUS, ORBIT_RADIUS, COLOR, DESCRIPTION)
  VALUES (4, 'Mars', 4, 160, 'rgb(189, 70, 63)', 'Fourth planet.');

INSERT INTO PLANET (ID, NAME, RADIUS, ORBIT_RADIUS, COLOR, DESCRIPTION)
  VALUES (5, 'Jupiter', 15, 180, 'rgb(225, 141, 131)', 'Fifth planet.');

INSERT INTO PLANET (ID, NAME, RADIUS, ORBIT_RADIUS, COLOR, DESCRIPTION)
  VALUES (6, 'Saturn', 10, 200, 'rgb(165, 139, 182)', 'Sixth planet.');

INSERT INTO PLANET (ID, NAME, RADIUS, ORBIT_RADIUS, COLOR, DESCRIPTION)
  VALUES (7, 'Uranus', 9, 220, 'rgb(173, 190, 179)', 'Seventh planet.');

INSERT INTO PLANET (ID, NAME, RADIUS, ORBIT_RADIUS, COLOR, DESCRIPTION)
  VALUES (8, 'Neptune', 7, 240, 'rgb(97, 152, 210)', 'Eight planet.');

INSERT INTO PLANET (ID, NAME, RADIUS, ORBIT_RADIUS, COLOR, DESCRIPTION)
  VALUES (9, 'Pluto', 3, 260, 'rgb(250, 228, 155)', '??? planet... Ok not a planet but including it anyway :)');